Add Linux (gcc) support (#109)
* fix gvk so that it compiles with gcc on linux

* make hello world compile, linker fails though

* set AVK_USE_VMA from CMake

* add todos

* fix imgui include file path

* clean up imgui includes

* replace std::runtime_error with gvk::runtime_error

* clean up sources and dependencies for gvk

* use std::snprintf also on Windows

* add todo

* add options for building examples (and corresponding targets)

* add option to control if assimp and glfw should be built as static or shared libraries

* add compiler check workflow

* fix typo

* convert to variable UNIX to bool

* install xorg-dev

* only run workflows on pull requests and on master, not on schedule

* don't build assimp and glfw samples, tools, etc

* don't append d to assimp shared lib name

* fix windows cmake build (release only)

* only define STB_IMAGE_IMPLEMENTATION when building with CMake

* add manual workflow dispatch

* add documentation for CMake

* copy shaders and assets after build instead of at configuration

* kickstart workflow on non-master branch

* start workflow -for real this time

* set options explicitly

* fix linux job, remove windows job

the windows job failed with
```
D:\a\Gears-Vk\Gears-Vk\auto_vk\src\avk.cpp : fatal error C1128: number of sections exceeded object file format limit: compile with /bigobj [D:\a\Gears-Vk\Gears-Vk\build\hello_world.vcxproj]
  Building Custom Rule D:/a/Gears-Vk/Gears-Vk/build/_deps/assimp-src/contrib/zlib/CMakeLists.txt
```
which I can't fix right now, since /bigobj should already be enabled.

* push now only triggers on master

* rename workflow

* use pre-built binaries on windows

* clean up

* add documentation of windows only options

* clean up cmake files

* add post build command script

* fix post build commands for windows

* add cmake settings for windows

* replace initialializer lists for clang

* add clang job

* mention clang in readme

* find assimp if it is installed

* refactor shader compilation so that changes to GLSL files are recognized by CMake

* fix import for external projects using Gears-Vk

* fix shader compilation such that the original directory structure is preserved in the spirv output directory

* use find_program to find glslangValidator

* adapt workflow name

* move format_for specialization due to include order related error on MSVC: explicit specialisation; format_for<vec<3,f32,highp> already instantiated

* dont look for specific file extensions when globbing for shaders

* go back to file extensions supported by glslangValidator

* remove remnants of cgb

* Update README.md

Co-authored-by: Johannes Unterguggenberger <johannes.unterguggenberger@gmail.com>

* fix typos: gcc -> GCC, clang -> Clang

* add newline

* set default library type to STATIC, precompile gvk.hpp such that AVK_USE_VMA doesn't have to be defined by the compiler

* Update README.md

Co-authored-by: Johannes Unterguggenberger <johannes.unterguggenberger@gmail.com>

* build stb as shared library on Linux

* remove status message

* add work-around for assimp in GitHub workflows

* Update README.md

Co-authored-by: Johannes Unterguggenberger <johannes.unterguggenberger@gmail.com>

* Update README.md

Co-authored-by: Johannes Unterguggenberger <johannes.unterguggenberger@gmail.com>

* Update README.md

Co-authored-by: Johannes Unterguggenberger <johannes.unterguggenberger@gmail.com>

* fix typos: Assimp -> ASSIMP

* Update README.md

Co-authored-by: Johannes Unterguggenberger <johannes.unterguggenberger@gmail.com>

* add missing file extensions when globbing for shaders

* add /bigobj and /MP to compile options for MSVC builds

* pin stb version on linux to 08e89524f693651819c4de2a29685b36301a08b1 - stb_perlin was removed after that

* ranges support requires c++latest on MSVC which is set for CMAKE_CXX_STANDARD 23

* Set compile options for Gears-Vk and dependents

* document resource management

* Apply suggestions from code review

Co-authored-by: Johannes Unterguggenberger <johannes.unterguggenberger@gmail.com>

* fix typo in asset file path

* fix typo in other file path

* Fixed string comparisons when `const char*` are stored.

* Initializing variables in orca_loader.cpp