fix linux job, remove windows job
the windows job failed with
```
D:\a\Gears-Vk\Gears-Vk\auto_vk\src\avk.cpp : fatal error C1128: number of sections exceeded object file format limit: compile with /bigobj [D:\a\Gears-Vk\Gears-Vk\build\hello_world.vcxproj]
  Building Custom Rule D:/a/Gears-Vk/Gears-Vk/build/_deps/assimp-src/contrib/zlib/CMakeLists.txt
```
which I can't fix right now, since /bigobj should already be enabled.